[package]
name = "RustKpi"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.1", features = ["full"] }
opencv = "0.94.4"
rayon = "1.11.0"
hc-sr04 = "0.1.2"
linux-embedded-hal = { version = "0.4", features = ["gpio_cdev"] }
pwm-pca9685 = "1.0.0"
dbscan = "0.3.1"
sdl2 = "0.36.0"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
pkg-config = "0.3"

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
panic = "abort"

[build]
rustflags = ["-C", "target-cpu=native"]
